<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '3c2f4c1540cf4624f1bdf756ba14ff2ed8456844',
        'name' => 'josemarcafumana/sistemalogin',
        'dev' => true,
    ),
    'versions' => array(
        'coffeecode/router' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../coffeecode/router',
            'aliases' => array(),
            'reference' => '29f73e12351a116e9bbb3f695595777a09e18077',
            'dev_requirement' => false,
        ),
        'josemarcafumana/sistemalogin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '3c2f4c1540cf4624f1bdf756ba14ff2ed8456844',
            'dev_requirement' => false,
        ),
        'league/plates' => array(
            'pretty_version' => 'v4.0.0-alpha',
            'version' => '4.0.0.0-alpha',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/plates',
            'aliases' => array(),
            'reference' => 'f53f4c1fa4bf307d0f3858a348172ff4faf7669a',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.0.7',
            'version' => '6.0.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => '0c41a36d4508d470e376498c1c0c527aa36a2d59',
            'dev_requirement' => false,
        ),
    ),
);
