<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'e9382c70f00025d1a642fc2b4686783f4f1b23ac',
        'name' => 'josemarcafumana/sistemalogin',
        'dev' => true,
    ),
    'versions' => array(
        'coffeecode/router' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../coffeecode/router',
            'aliases' => array(),
            'reference' => '29f73e12351a116e9bbb3f695595777a09e18077',
            'dev_requirement' => false,
        ),
        'josemarcafumana/sistemalogin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'e9382c70f00025d1a642fc2b4686783f4f1b23ac',
            'dev_requirement' => false,
        ),
        'league/plates' => array(
            'pretty_version' => 'v4.0.0-alpha',
            'version' => '4.0.0.0-alpha',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/plates',
            'aliases' => array(),
            'reference' => 'f53f4c1fa4bf307d0f3858a348172ff4faf7669a',
            'dev_requirement' => false,
        ),
    ),
);
